### ISSUE TITLE
why it wasn't made public until now?

### ISSUE THREAD

**Issue by dzylikecode** [worranhin/machanism-drafter#1]
😡

**Comment by worranhin** [comment]
Because it isn't complete yet. 😅

**Comment by dzylikecode** [comment]
just an excuse 😡

**Comment by worranhin** [comment]
You are right.  I just cleared up my repos last night and found this one unconsciously. It was lost deep in the ocean of memory until then. 😆

**Comment by dzylikecode** [comment]
alright
